### ISSUE TITLE
Notes Not Required for Phone Call

### ISSUE THREAD

**Issue by aarontitus** [CrisisCleanup/crisiscleanup-3-web#1441]
When closing out a phone call (inbound or outbound), the user must choose a call status. This is correct. However, they are also required to add notes. Notes should not be required to close out a phone call.

**Comment by BradenM** [comment]
@aarontitus 

FYI:

If I recall correctly, this was done because (on the prior system) if an agent did not write a note themselves, one was auto-generated for purposes of having an entry to the case history about the phone call. (not that this means notes should be required, but that the fact that it was required wasn't an issue).

I can't remember exactly what it said, but probably something along the lines of "Called at <some time" and ended with <some status>." 

I don't know if this is being handled a different way or is not wanted now, but figured I should mention it

**Comment by aarontitus** [comment]
@BradenM Thanks. I'm sure it was deliberate. We've since discovered that it's not needed, and creates more problems than it solves. Background always helps :-).

**Comment by aarontitus** [comment]
Not sure how to test this one, except in the live environment.
