### ISSUE TITLE
Warn Internet Explorer Users to get a real Browser

### ISSUE THREAD

**Issue by arroyoDev** [CrisisCleanup/crisiscleanup-3-web#702]
add the warning (suggestion) in the batter up to to change to something that works. 

"~~This website does not support Internet Explorer. We recommend using a modern browser like Firefox, Chrome, Edge, etc."

**Comment by BradenM** [comment]
See #703 

![iemock_dash](https://user-images.githubusercontent.com/5913808/82746304-dc2cee80-9d53-11ea-861c-ac4dcbff1ea6.gif)
![iemock_home](https://user-images.githubusercontent.com/5913808/82746305-dc2cee80-9d53-11ea-9c57-6504884e3d0f.gif)

**Comment by aarontitus** [comment]
Re-opening for one primary reason, and one secondary reason:
1. Please add the proper $18n.t() code to have the string translated, so that I can copy and paste the translated string.
2. I am not able to confirm this works, because when I open either the dev or live site in IE, the page does not load at all. It would be nice to confirm that it works in a non-forced scenario.

**Comment by BradenM** [comment]
> Please add the proper $18n.t() code to have the string translated, so that I can copy and paste the translated string.

Translation takes place right before the banner is rendered:
https://github.com/CrisisCleanup/crisiscleanup-3-web/blob/3ea92519c0919c82ae62daebc8a9348ed297b0de/src/components/notifications/BannerOverlay.vue#L5-L7

So your good to add the translation here:
https://github.com/CrisisCleanup/crisiscleanup-3-web/blob/3ea92519c0919c82ae62daebc8a9348ed297b0de/src/store/modules/ui/actions.js#L24-L27

> I am not able to confirm this works, because when I open either the dev or live site in IE, the page does not load at all. It would be nice to confirm that it works in a non-forced scenario.

Ah duh. Might be hard to see a banner when you can't see anything at all. Fixing.
